# Generated by Django 5.2.15 on 2026-09-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion Utilisateur'), ('TRIAL_START', "Démarrage d'une épreuve"), ('TRIAL_SUBMITTED', "Soumission d'épreuve"), ('TRIAL_EXPIRED', 'Expiration du chronomètre'), ('GRADE_PRACTICAL', 'Notation manuelle par le jury'), ('TRIAL_STATUS_CHANGE', "Modification du statut d'une épreuve"), ('SETTINGS_CHANGE', 'Modification des paramètres de compétition'), ('OTHER', 'Autre action')], default='OTHER', max_length=40, verbose_name='Action')),
                ('description', models.TextField(verbose_name="Détails de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date & Heure')),
            ],
            options={
                'verbose_name': "Journal d'activité (Audit Log)",
                'verbose_name_plural': "Journaux d'activités",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(default='TeCoX Digital Challenge 2026', max_length=200, verbose_name='Nom officiel de la compétition')),
                ('edition', models.CharField(default='Édition 2026', max_length=50, verbose_name='Édition')),
                ('is_leaderboard_public', models.BooleanField(default=True, verbose_name='Rendre le classement public pour les participants')),
                ('is_competition_active', models.BooleanField(default=True, verbose_name='Compétition active en cours')),
                ('allow_registrations', models.BooleanField(default=False, verbose_name='Autoriser les inscriptions publiques')),
                ('banner_message', models.TextField(blank=True, default='', verbose_name="Message d'annonce / Bannière générale")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de la compétition',
                'verbose_name_plural': 'Paramètres de la compétition',
            },
        ),
    ]
