# Generated by Django 5.2.15 on 2026-09-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, default='', verbose_name='Réponse textuelle ou numérique saisie')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='participant_submissions/%Y/%m/', verbose_name='Fichier déposé pour la mission')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier original')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Taille du fichier (octets)')),
                ('score_awarded', models.FloatField(default=0.0, verbose_name='Points attribués')),
                ('is_graded', models.BooleanField(default=False, verbose_name='Est corrigée')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Est correcte (évaluation auto)')),
                ('jury_feedback', models.TextField(blank=True, default='', verbose_name='Commentaire / Remarque du Jury')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure de correction')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['question__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Non commencée'), ('in_progress', 'En cours'), ('submitted', 'Soumise (En attente de correction)'), ('graded', 'Corrigée'), ('expired', 'Expirée (Temps écoulé)'), ('abandoned', 'Abandonnée')], db_index=True, default='in_progress', max_length=20, verbose_name='Statut de la tentative')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Débutée le')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumise le')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Temps passé (secondes)')),
                ('auto_score', models.FloatField(default=0.0, verbose_name='Score automatique (QCM/Direct)')),
                ('manual_score', models.FloatField(default=0.0, verbose_name='Score manuel (Missions pratiques)')),
                ('total_score', models.FloatField(db_index=True, default=0.0, verbose_name='Score total obtenu')),
                ('max_possible_score', models.FloatField(default=100.0, verbose_name='Score total maximum possible')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Pourcentage de réussite (%)')),
                ('is_final', models.BooleanField(default=True, verbose_name='Tentative retenue pour le classement final')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent / Navigateur')),
            ],
            options={
                'verbose_name': 'Tentative',
                'verbose_name_plural': 'Tentatives',
                'ordering': ['-started_at'],
            },
        ),
    ]
