# Generated by Django 5.2.15 on 2026-09-01 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL, verbose_name='Corrigé par'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='competitions.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='selected_in_answers', to='competitions.option', verbose_name='Options cochées'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='competitions.trial', verbose_name='Épreuve'),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.attempt', verbose_name='Tentative'),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('participant', 'trial')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
