# Generated by Django 5.2.15 on 2026-09-01 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'QCM Choix Unique'), ('MULTIPLE_CHOICE', 'QCM Choix Multiples'), ('TRUE_FALSE', 'Vrai / Faux'), ('SHORT_TEXT', 'Réponse Courte'), ('NUMERIC', 'Réponse Numérique'), ('PRACTICAL', 'Mission Pratique (Dépôt de fichier)')], default='SINGLE_CHOICE', max_length=25, verbose_name='Type de question')),
                ('prompt', models.TextField(verbose_name='Énoncé de la question')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name="Image / Schéma d'illustration")),
                ('attachment', models.FileField(blank=True, null=True, upload_to='trial_attachments/', verbose_name='Fichier / Ressource à télécharger par le participant')),
                ('attachment_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom affiché de la ressource')),
                ('points', models.FloatField(default=10.0, verbose_name='Nombre de points attribués')),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'apparition")),
                ('difficulty', models.CharField(choices=[('EASY', 'Facile'), ('MEDIUM', 'Moyen'), ('HARD', 'Difficile')], default='MEDIUM', max_length=15, verbose_name='Niveau de difficulté')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explication / Corrigé pour le jury ou participant')),
                ('practical_instructions', models.TextField(blank=True, default='', verbose_name='Consignes précises de la mission pratique')),
                ('practical_allowed_extensions', models.CharField(default='.docx,.xlsx,.pptx,.pdf,.zip,.png,.jpg', max_length=100, verbose_name='Extensions de fichiers autorisées pour le dépôt')),
                ('correct_text_answer', models.CharField(blank=True, default='', max_length=255, verbose_name='Réponse textuelle ou numérique exacte attendue')),
                ('is_case_sensitive', models.BooleanField(default=False, verbose_name='Sensible à la casse (majuscules/minuscules)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question / Mission',
                'verbose_name_plural': 'Questions & Missions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'épreuve")),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('INFORM_GEN', 'Informatique Générale'), ('SMARTPHONE', 'Téléphone Portable / Smartphone'), ('ORDINATEUR', 'Ordinateur & Matériel'), ('WINDOWS', 'Système Windows'), ('WORD', 'Microsoft Word'), ('EXCEL', 'Microsoft Excel'), ('POWERPOINT', 'Microsoft PowerPoint'), ('GRAND_CHALLENGE', 'Grand Challenge TDC'), ('AUTRE', 'Autre Compétence')], default='INFORM_GEN', max_length=30, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='Consignes générales')),
                ('duration_minutes', models.PositiveIntegerField(default=20, help_text='0 pour illimité', verbose_name='Durée allouée (en minutes)')),
                ('max_score', models.FloatField(default=100.0, verbose_name='Score barème maximum')),
                ('weight', models.FloatField(default=1.0, verbose_name="Poids / Coefficient de l'épreuve")),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage / Épreuve N°")),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SCHEDULED', 'Programmée'), ('OPEN', 'Ouverte (Prête)'), ('IN_PROGRESS', 'En cours de passage'), ('COMPLETED', 'Terminée'), ('ARCHIVED', 'Archivée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure de début')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure de fin')),
                ('allow_multiple_attempts', models.BooleanField(default=False, verbose_name='Autoriser plusieurs tentatives')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name="Mélanger l'ordre des questions")),
                ('show_results_immediately', models.BooleanField(default=False, verbose_name='Afficher le corrigé immédiatement après soumission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texte du choix')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Est la bonne réponse')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='competitions.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option de réponse',
                'verbose_name_plural': 'Options de réponses',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competitions.trial', verbose_name='Épreuve'),
        ),
    ]
